Ensure a consistent chain ID between a signer and provider in SignerMiddleware
gakonst/ethers-rs pull request #1095
Opened 2022-03-30 00:35 UTC by Rjected

## Motivation

Frequently users run into errors returned by a `Provider` that are caused by chain ID inconsistencies between the user's `Signer` and `Provider`. For example, if the user tries to sign/send a transaction using a `SignerMiddleware` instantiated with a `Signer` and `Provider` that have different chain IDs, they might get this error from the provider:
```
Error: (code: -32700, message: Invalid signature v value, data: None)
```
Since users often use a `SignerMiddleware` to interact with both a provider and signer, it would be useful to ensure that the `Signer` uses the same chain ID as the `Provider`, to prevent this type of user error. [Other approaches were discussed in a different issue](https://github.com/gakonst/ethers-rs/pull/879#issuecomment-1032994226).

## Solution

Update the `SignerMiddleware` constructor and `with_signer` method to set the passed `Signer`'s chain ID to the ID retrieved from the provider.
This changes the following `SignerMiddleware` methods:

**Old**:
```rust
    pub fn new(inner: M, signer: S) -> Self {
        // constructor...
    }

    pub fn with_signer(&self, signer: S) -> Self {
        // implementation...
    }
```
**New**:
```rust
    pub async fn new(inner: M, signer: S) -> Result<Self, SignerMiddlewareError<M, S>> {
        // constructor...
        // pulls the chain id from the inner middleware
    }

    pub async fn with_signer(&self, signer: S) -> Result<Self, SignerMiddlewareError<M, S>> {
        // implementation...
    }
```
We also have removed the `#[must_use]` attribute from `with_signer`, since [it doesn't do anything for async functions](https://github.com/rust-lang/rust/issues/78149).

Importantly, if a `chain_id` cannot be retrieved from the provider (due to a provider error or some other reason), we bubble up the error.

Previously, the implementation details of the provider were not relevant to the creation of a `SignerMiddleware`.
Now, **the `SignerMiddleware` _must_ be constructed with a provider with an implemented and working `get_chainid` method**, or `new`/`with_signer` will return an error rather than a new `SignerMiddleware`.

Additionally, **this breaks current uses of `SignerMiddleware`**, since the `Result` must be handled, and each method is now `async`, since we're now interacting with a provider.

Tests are added which set a custom chain ID for Ganache and make sure the signer properly pulls the custom chain ID. To set a chain ID on Ganache, it had to be updated. There may be some differences in behavior between the two versions, so we should watch for test failures [after re-enabling the relevant section of CI](https://github.com/gakonst/ethers-rs/blob/3a653472cfb484bab7ae831ad6e3664d24b4e916/.github/workflows/ci.yml#L179).

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [x] Updated the changelog

2022-03-30 01:00 UTC, Rjected commented
Seems like the updated ganache behaves differently and [caused the run to fail](https://github.com/gakonst/ethers-rs/runs/5746590085?check_suite_focus=true), the test probably needs to be updated:
```
failures:

---- eth_tests::deploy_and_call_contract stdout ----
thread 'eth_tests::deploy_and_call_contract' panicked at 'assertion failed: `(left == right)`
  left: `56568`,
 right: `38856`', ethers-contract/tests/contract.rs:72:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    eth_tests::deploy_and_call_contract

test result: FAILED. 34 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 14.91s

error: test failed, to rerun pass '-p ethers-contract --test contract'
```

2022-03-30 09:07 UTC, mattsse reviewed
cc @gakonst

2022-03-30 09:07 UTC, mattsse commented on ethers-middleware/src/signer.rs
> +    pub async fn new(inner: M, signer: S) -> Result<Self, SignerMiddlewareError<M, S>> {
this is definitely an improvement but this breaks, and will be redundant if the user manually sets the chain id without requesting it from the inner middleware.

I'd rather like to make this a separate asynchronous function that does this. basically with_signer

2022-03-30 09:07 UTC, mattsse commented on ethers-middleware/tests/signer.rs
> +    let provider = SignerMiddleware::new(provider, wallet).await.unwrap();
here for example, in this scenario, we're now querying the chain id twice

2022-04-02 02:05 UTC, gakonst commented
I think moving to a new method instead of a breaking change makes sense here. Not sure what the best name for the function is, something that declares that it auto detects chain id ideally

2022-04-10 01:13 UTC, Rjected commented
Just switched to a new method `new_with_provider_chain`:
```rust
/// Creates a new client from the provider and signer.
/// Sets the address of this middleware to the address of the signer.
/// Sets the chain id of the signer to the chain id of the inner [`Middleware`] passed in,
/// using the [`Signer`]'s implementation of with_chain_id.
///
/// [`Middleware`] ethers_providers::Middleware
/// [`Signer`] ethers_signers::Signer
pub async fn new_with_provider_chain(
    inner: M,
    signer: S,
) -> Result<Self, SignerMiddlewareError<M, S>> {
    let address = signer.address();
    let chain_id =
        inner.get_chainid().await.map_err(|e| SignerMiddlewareError::MiddlewareError(e))?;
    let signer = signer.with_chain_id(chain_id.as_u64());
    Ok(SignerMiddleware { inner, signer, address })
}
```
Edited the comment on `new` to point to this method & explain what might happen if the chainid is not consistent.
Also needed to [remove an assert in `deploy_and_call_contract`](https://github.com/gakonst/ethers-rs/pull/1095/files#diff-f7ed5ca95548046c8f53e9acec04d1412a8e5db4cece5f3500be57c7a8067359L72) since the gas used & estimation are no longer equal with the updated ganache.

2022-04-10 16:19 UTC, gakonst requested changes
Need to remove the formatting change in the doc comments, otherwise lgtm

2022-04-10 16:19 UTC, gakonst commented on ethers-middleware/src/signer.rs
> +///     let provider = Provider::<Http>::try_from("http://localhost:8545")
These indents shouldn't be required?

2022-04-10 16:50 UTC, Rjected commented on ethers-middleware/src/signer.rs
> +///     let provider = Provider::<Http>::try_from("http://localhost:8545")
whoops yeah

2022-04-10 16:57 UTC, Rjected commented
Removed indents and rebased

2022-04-10 17:54 UTC, gakonst approved these changes
gg thx!

2022-04-10 17:55 UTC, merged