Generate structs for the return data of abigen-erated contracts
gakonst/ethers-rs pull request #1440
Opened 2022-06-30 23:16 UTC by joleeee

## Motivation
I explain the usecase in #1405, the short version is that you cannot easily decode the return of calls without an instatiated contract (`::new()` with a provider). Since abigen already generates structs representing calls, which AbiEncode into bytes, it only makes sense it should also have structs that AbiDecode the return data into a usable response representation.

## Solution
I hope the code is mostly self explanitory. Since I am to contributing here, I'd love some feedback on the stuff i did so far.

I'm wondering if you'd want there to be an enum for return structs when there is more than one, like with the calls? I can put it back in but i initially removed it.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

2022-07-01 00:32 UTC, gakonst commented
like the direction - could you also add some tests for this?

2022-07-01 14:23 UTC, joleeee commented
I made a test now, let me know if it is satisfactory or what else should be tested. Note that this will not generate return bindings for functions that do not return anything.

2022-07-01 14:46 UTC, mattsse requested changes
this only _generates_ structs, right?

this still does not replace the return type of the contract calls, right? those are still tuples?

2022-07-01 14:46 UTC, mattsse commented on ethers-contract/ethers-contract-abigen/src/contract/methods.rs
> +        if function.outputs.len() < 1 {
```suggestion
        if function.outputs.is_empty() {
```

2022-07-01 14:55 UTC, joleeee commented
That is correct, this only adds additional structs, it does not change the call-bindings in any way.

2022-07-04 10:52 UTC, mattsse approved these changes
lgtm

this should not break anything, since this merely generates new types

2022-07-04 18:54 UTC, merged