Implement fastrlp traits for Signature
gakonst/ethers-rs pull request #1444
Opened 2022-07-01 21:14 UTC by Rjected

## Motivation

Deriving fastrlp `Encodable` and `Decodable` traits for types that contain `Signature` would not be possible without implementing `Encodable` and `Decodable` for `Signature`.

## Solution

 * Add `fastrlp` as a dependency to `ethers-core`, meaning this conflicts with #1443 for the time being
 * Implement `Hash` on `Signature` (just a convenience impl, not related to fastrlp traits)
 * Implement RLP encoding and decoding for `Signature`. This does not encode or decode a RLP header for a signature type, since types that would contain a signature (for example a [signed transaction](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-encoding-and-validity)) are usually encoded as `[...rest of object, v, r, s]` rather than `[...rest of object, [v, r, s]]`.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

2022-07-02 20:00 UTC, gakonst requested changes

2022-07-02 20:00 UTC, gakonst commented on ethers-core/Cargo.toml
> +fastrlp = { git = "https://github.com/vorot93/fastrlp", features = ["std", "derive", "ethereum-types"] }
Is there a released version we can use?

2022-07-04 17:17 UTC, Rjected commented on ethers-core/Cargo.toml
> +fastrlp = { git = "https://github.com/vorot93/fastrlp", features = ["std", "derive", "ethereum-types"] }
bumped to `0.1.2`

2022-07-04 18:13 UTC, gakonst approved these changes

2022-07-04 18:13 UTC, merged