Update README to document common feature flags for providers (websock…
gakonst/ethers-rs pull request #1493
Opened 2022-07-21 07:14 UTC by dbelv

…ets, ipc and https)

## Motivation

Address issue #1261. Including additional information for ipc.

## Solution

Update the README with a Providers section detailing the common feature flags.

## PR Checklist

- [ ] Added Tests (N/A)
- [ ] Added Documentation
- [ ] Updated the changelog (N/A)

I didn't update the changelog as there wasn't a good place to include this and I wasn't sure (given the existing entries) if a global section wanted to be included.

2022-07-21 10:12 UTC, mattsse requested changes

2022-07-21 10:12 UTC, mattsse commented on README.md
> +ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["openssl", "rustls"] }
I would rather recommend either-or. Enabling both doesn't make much sense.

so let's simply add two toml examples for openssl and rustls

2022-07-21 10:12 UTC, mattsse commented on README.md
> +If you are looking to connect to a HTTPS endpoint, then you need to enable TLS (`rustls`) and/or SSL (`openssl`)
```suggestion
If you are looking to connect to a HTTPS endpoint, then you need to enable the `rustls` or `openssl` feature.
```

2022-07-21 11:02 UTC, mattsse approved these changes
awesome, ty!

2022-07-24 01:20 UTC, gakonst approved these changes

2022-07-24 01:20 UTC, merged