Feat/multicall3
gakonst/ethers-rs pull request #1584
Opened 2022-08-09 22:40 UTC by DaniPopes

## Motivation

Closes: #1576 

## Solution

Missing tests.

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [ ] Updated the changelog

2022-08-10 20:19 UTC, gakonst commented
@mds1 @mattsse wdyt?

2022-08-10 20:22 UTC, mds1 commented
Supportive, I agree with all the rationale in #1576 which was the motivation for Multicall3

2022-08-10 23:32 UTC, DaniPopes commented
Looks like we need to lock the entire `Multicall` module behind the `abigen` feature.. unless there's a way to generate the contract binding without the `derive`s?

2022-08-12 00:20 UTC, DaniPopes commented
^ CC @mattsse @gakonst - new contract binding requires the derive macros from `ethers-contract-derive` which needs the `abigen` feature to be enabled

2022-08-12 01:10 UTC, gakonst commented
Hmm should we just stop feature gating abigen as a feature altogether? @mattsse i always seem to need it

2022-08-19 16:04 UTC, mattsse requested changes
sorry, this one slipped through.

some nits, but lgtm in general

2022-08-19 16:04 UTC, mattsse commented on ethers-contract/src/multicall/mod.rs
> +                            } else if ret.is_empty() {
can use `String::decode(&ret[4..])` here
with `AbiDecode`

2022-08-19 16:04 UTC, mattsse commented on ethers-contract/src/multicall/multicall_contract.rs
> +        pub use ethers_contract_derive::*;
this reexport seems wrong

this reexports the derive macros not the traits

2022-08-19 17:01 UTC, mattsse approved these changes
docs + test lgtm

2022-08-28 19:18 UTC, gakonst approved these changes
LGTM - it does add an extra param on add_call but should be ok

2022-08-28 19:18 UTC, merged