enhance signer middleware to automatically switch legacy
gakonst/ethers-rs pull request #1832
Opened 2022-11-04 04:49 UTC by kristian1108

## Motivation

If you try to use SignerMiddleware on chains that don't support EIP-1559 (Optimism, BSC, etc), you'll get an error. Client code has to check the chain id everywhere, which is fragile and annoying. The middleware should automatically handle this, especially since the chain information is already stored in ethers-rs.

## Solution

Parse Chain from chain_id. Check if it's a "legacy only" chain. If so, convert the transaction to a legacy transaction as part of the fill logic.

## PR Checklist

-   [x] Added Tests
-   [x] Added Documentation
-   [] Updated the changelog  --> not sure what to do here?

2022-11-04 08:27 UTC, mattsse requested changes

2022-11-04 08:27 UTC, mattsse commented on ethers-middleware/src/signer.rs
> +            let tx_chain_id = tx.chain_id().unwrap(); // safe unwrap after is_some check above
use if let

2022-11-04 08:27 UTC, mattsse commented on ethers-middleware/src/signer.rs
> +            if chain.is_ok() && chain.unwrap().is_legacy() {
can simplify with unwrap_or_default

2022-11-04 08:27 UTC, mattsse commented on ethers-middleware/src/signer.rs
> +                *tx = legacy_tx;
this clone is unnecessary if already legacy.
match via `ref` should work here and clone if eip1559

2022-11-04 17:38 UTC, mattsse approved these changes
ty, lgtm.

this is a reasonable additional check imo.

smol pedantic nits

2022-11-04 17:38 UTC, mattsse commented on ethers-middleware/src/signer.rs
> +            if chain.unwrap_or_default().is_legacy() {
```suggestion
            if chain.map(Chain::is_legacy).unwrap_or_default() {
```

2022-11-04 17:38 UTC, mattsse commented on ethers-middleware/src/signer.rs
> +                    *tx = TypedTransaction::Legacy(i_tx);
```suggestion
                    let tx_req: TransactionRequest = inner.clone().into();
                    *tx = TypedTransaction::Legacy(tx_req);
```

2022-11-07 20:27 UTC, gakonst approved these changes
nice! thank you

2022-11-07 20:27 UTC, merged