Fix: use cwd manifest
gakonst/ethers-rs pull request #1869
Opened 2022-11-17 18:43 UTC by Will-Smith11

## Motivation
the previous fix used CARGO_MANIFEST_DIR however this turns out to return the crate directory rather than the dependant crate directory making this impl wrong 

## Solution
use the cwd instead. This doesn't cover all cases but is better than the current which misses all the cases

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog

2022-11-17 18:44 UTC, gakonst requested changes
can we please add some tests for this on the edge cases?

2022-11-17 18:48 UTC, mattsse approved these changes
this should be enough, can revise once edge cases come up

2022-11-17 19:23 UTC, gakonst commented
Let's just merge so we get this out, but let's follow up with a test PR

2022-11-17 19:23 UTC, merged

2022-11-20 21:58 UTC, gakonst commented
I think this. MAY have broken docs.rs builds https://docs.rs/crate/ethers/1.0.1/builds/679442?

2022-11-21 10:21 UTC, mattsse commented
hmm don't think so since this is shouldn't be used during macro expansion.