fix: remove `OpCode` enum and update `VMOperation`'s `op` field
gakonst/ethers-rs pull request #1904
Opened 2022-11-28 04:12 UTC by mouseless-eth

## Motivation

Addresses #1902

Ensures that tracing with VmTrace enabled will continue to be future proof in the presence of any opcodes added/removed when ethereum undergoes a new hardfork.

## Solution

Removed the ethers::core::types::OpCode enum by deleting [it's source file](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/trace/opcodes.rs#L70)

Changed VMOperation's op field to be of type string.

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog

2022-11-28 13:44 UTC, mattsse approved these changes
imo this is probably easier to maintain than an enum, so I'm supportive of this,

2022-11-30 21:21 UTC, gakonst commented
Should we instead do `enum Opcode { Known(Opcode), Unknown(String)`?

2022-12-01 06:32 UTC, mouseless-eth commented
> Should we instead do `enum Opcode { Known(Opcode), Unknown(String)`? I like the ability to match.

This route looks like a valid solution to unwanted serialization errors - I will work on implementing it, and we can test how it works.

2022-12-02 20:11 UTC, gakonst requested changes
typo on the type, lgtm otherwise

2022-12-02 20:11 UTC, gakonst commented on ethers-core/src/types/trace/mod.rs
> +                ExectuedInstruction::Known(Opcode::GAS),
```suggestion
                ExecutedInstruction::Known(Opcode::GAS),
```

2022-12-02 20:47 UTC, mouseless-eth reviewed
Good catch, typo has been fixed

2022-12-02 20:51 UTC, merged

2022-12-02 20:51 UTC, mouseless-eth reviewed
forgot to add files to prev comment