Fixes #1899
gakonst/ethers-rs pull request #1905
Opened 2022-11-28 21:01 UTC by mouseless-eth

## Motivation

Fixes #1899 

## Description of problem

The error occurs due to `TxpoolInspectSummary`'s deserialize method not having a way to parse the following response

```
"0x00000000863B56a3C1f0F1be8BC4F8b7BD78F57a": {
  "40": "contract creation: 0 wei + 612412 gas × 6000000000 wei"
}

```
## Solution
- Add a new match arm to map "contract creation" into None (as specified [here](https://github.com/gakonst/ethers-rs/blob/79e64a8378891df5afc6b83f75059c5afc587ae1/ethers-core/src/types/txpool.rs#L11)) when deserializing  `TxpoolInspectSummary`'s `to` field

- Rewrite tests to account for deserializing and serializing logs that include a contract creation

## PR Checklist

-   [x] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog

2022-11-28 21:55 UTC, mattsse reviewed
interesting, do you know where geth has this implemented?

2022-11-28 21:55 UTC, mattsse commented on ethers-core/src/types/txpool.rs
> +        };
nit: use if let Some() else here

2022-11-28 22:40 UTC, gakonst commented
wonder if this is from a non-ethereum geth impl. i def tested it with real geth data when i wrote the feat

2022-11-29 00:17 UTC, mouseless-eth commented on ethers-core/src/types/txpool.rs
> +        };
Thank you for the tip, made the edit

2022-11-29 00:22 UTC, mouseless-eth commented
> interesting, do you know where geth has this implemented?

Seems to be implemented here at [go-ethereum/internal/ethapi/api.go](https://github.com/ethereum/go-ethereum/blob/8c5ce1107b3110c7cb735d8dfa91c9c701393c85/internal/ethapi/api.go#L235)

2022-11-29 00:25 UTC, mouseless-eth commented
> wonder if this is from a non-ethereum geth impl. i remember we had tested this with real geth data when the feature was implemented

Erigon does not have support for the `txpool_inspect` rpc (they chose to [comment it out](https://github.com/ledgerwatch/erigon/blob/76c36c2c0992ff2c1f410be03ddb3752434e410b/cmd/rpcdaemon/commands/txpool_api.go#L138) for some reason). Not sure about other node clients though

2022-11-29 01:09 UTC, estarriolvetch commented
Hey @mouseless-eth 

Thank you for the help!

I am trying to use your version to see if it works. However, I'm still getting the same result. Below is my code.

```main.rs
use std::io;
use std::io::prelude::*;
use std::ops::Mul;
use std::{thread, time::Duration};
use std::fs;
use std::{convert::TryFrom, path::Path, sync::Arc};
use ethers::{prelude::*};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let provider = Provider::<Http>::try_from(
        // Test URL from quicknode docs
        "https://blue-light-gas.quiknode.pro/bc95fc4c322283e8b472d43143658e5673cbb631/",
    )?;

    let content = provider.txpool_inspect().await?;
    println!("{content:?}");
    Ok(())
}
```

```
[dependencies]
ethers = { git="https://github.com/mouseless-eth/ethers-rs", branch="fix/txpool_inspect" }
tokio = { version = "1.22", features = ["full"] }
```

2022-11-29 01:13 UTC, estarriolvetch commented
Actually, I'm getting a different error now.

```
Error: JsonRpcClientError(SerdeJson { err: Error("number too large to fit in target type", line: 1, column: 1550516), text: "{\"pe
```

2022-11-29 01:53 UTC, estarriolvetch commented
The full error is here:
https://gist.github.com/estarriolvetch/273d3188f7f0a61fbf2512740923746c

2022-11-29 03:13 UTC, mouseless-eth commented
> Actually, I'm getting a different error now.
> 
> ```
> Error: JsonRpcClientError(SerdeJson { err: Error("number too large to fit in target type", line: 1, column: 1550516), text: "{\"pe
> ```

Thanks for testing the branch and bringing the new error to attention

I isolated the error to this instance from the logs you shared
```
"0x307Ad9cbEB9ff143806cF163A79D26c9f13F8418": {
  "357": "0xab5558Fc3ac543433b15E70D84e6Ac11De74E512: 26000000000000000000 wei + 21100 gas × 10000000000 wei",
  "358": "0xab5558Fc3ac543433b15E70D84e6Ac11De74E512: 26000000000000000000 wei + 21100 gas × 9000000000 wei",
  "359": "0xab5558Fc3ac543433b15E70D84e6Ac11De74E512: 26000000000000000000 wei + 21100 gas × 9000000000 wei"
}
``` 

The error originates from the fact that the value sent (**26000000000000000000** wei) is greater than `u64::MAX` so when [`u64::from_str(value_split[0])`](https://github.com/gakonst/ethers-rs/blob/79e64a8378891df5afc6b83f75059c5afc587ae1/ethers-core/src/types/txpool.rs#L67) is called, it returns the error mentioned above

I bumped all u64 types to u128 for all variables that rely on `u64::from_str` to convert a string into a number (`value`, `gas`, `gas_price`), which should solve the problem (also bumped u64->u128 in tests just for consistency although makes no difference)

2022-11-29 04:01 UTC, DaniPopes requested changes

2022-11-29 04:01 UTC, DaniPopes commented on ethers-core/src/types/txpool.rs
>                  Some(Address::from_str(&addr.to_string().split_off(2)).map_err(de::Error::custom)?)
```suggestion
                Some(Address::from_str(addr.trim_start_matches("0x")).map_err(de::Error::custom)?)
```

2022-11-29 06:25 UTC, mouseless-eth commented on ethers-core/src/types/txpool.rs
> +        let gas_price = U256::from(u128::from_str(gas_price_split[0]).map_err(de::Error::custom)?);
Nice edits, much cleaner code.

You mention a good point however most other data types ([`TypedTransaction`](https://docs.rs/ethers/latest/ethers/types/transaction/eip2718/enum.TypedTransaction.html#method.gas), [`provider::get_gas_price`](https://docs.rs/ethers/latest/ethers/providers/struct.Provider.html#method.get_gas_price), [`ContractDeployer`](https://docs.rs/ethers/latest/ethers/contract/struct.ContractDeployer.html#method.gas), ...) use U256 for both `gas` and `gas_price` - might be better to keep U256 for consistency. But [`GethTrace`](https://docs.rs/ethers/latest/ethers/types/struct.GethTrace.html#structfield.gas) and [`StructLog`](https://docs.rs/ethers/latest/ethers/core/types/struct.StructLog.html) do use u64 for `gas`

2022-11-29 21:18 UTC, gakonst approved these changes
clean - good catch, thank you.

2022-11-29 21:18 UTC, merged