Fix: handle panic on Ws error
gakonst/ethers-rs pull request #1915
Opened 2022-12-01 00:02 UTC by 0xMelkor

## Motivation
Some issues have been raised, reporting `WsServer` panics on upstream connection errors. 
#1889 #1815
https://github.com/gakonst/ethers-rs/blob/4b685621ed3a4b827276a13107f30457a19379db/ethers-providers/src/transports/ws.rs#L250-L256

## Solution
In order to have a simpler and more predictable behavior, I believe the application should directly handle reconnections (as stated [here](https://github.com/snapview/tokio-tungstenite/issues/101)), avoiding recovery mechanisms at the transport layer.

Instead of crashing the program, we gracefully close all active subscriptions. Clients will then observe the end of their streams and issue proper actions.

NOTE
I need to add some unit tests, so I leave this in a DRAFT state.

What do you guys think?

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog

2022-12-01 14:54 UTC, mattsse requested changes
imo, it makes more sense to handle this gracefully and don't panic on the ws task.

needs changelog entry

2022-12-01 15:09 UTC, 0xMelkor commented
Hi @mattsse, changelog updated.

2022-12-01 19:00 UTC, gakonst approved these changes
LGTM - let's iterate on this @mattsse so we unblock @0xMelkor

2022-12-01 19:00 UTC, merged

2023-01-16 14:25 UTC, Tigranchick commented
Sorry for the dumb question, but how can I catch this panic or error, i mean is there place to match it. I don't get messages from websocket often and it breaks with connection refused. Now I took one of the solutions with 2 loops and a timeout in tokio select! like there #1889 .

2023-01-16 15:34 UTC, 0xMelkor commented
Hi @Tigranchick,

this PR removed the `panic!` statement in `ws.rs`, in favor of a graceful teardown of active subscriptions. The effect is that your stream  reaches the last element and you are up to handle reconnections.

```rust
    // This loop iterates over WebSocket disconnections
    'connection: loop {

        let client = Provider::<Ws>::connect("wss://your-uri").await?;
        let client = Arc::new(client);
        let filter = Filter::new().event("Transfer(address,address,uint256)");

        let mut stream = client.subscribe_logs(&filter).await?;

        while let Some(log) = stream.next().await {
                 // Do some work
        }
       
        // If you get here, your subscription has been canceled => Iterate over the main loop to handle reconnection
   }
```

### How can we improve ethers in my opinion
A cleaner approach would also propagate errors from Ws to the application. 
This requires some library changes along the stack, and the subscription code would become like:

```rust
        // The stream now emits `Result`instead of `Log`
        while let Some(result) = stream.next().await {
                 match result {
                     Ok(log) => // Do some work
                     Err(e) => // Handle the errror
                 }
        }
```

2023-01-21 22:14 UTC, Tigranchick commented
@0xMelkor, thanks you to explanation!