add_calls and call_array for Multicall
gakonst/ethers-rs pull request #1941
Opened 2022-12-15 17:47 UTC by onsails

## Motivation

## Solution

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

2022-12-16 07:41 UTC, mattsse requested changes
I like this,

some nits, also needs nightly formatting `cargo +nightly fmt`

2022-12-16 07:41 UTC, mattsse commented on ethers-contract/src/multicall/mod.rs
> +        calls: Vec<ContractCall<M, D>>,
let's accept an impl IntoIterator here and switch the order of args

2022-12-16 07:41 UTC, mattsse commented on ethers-contract/tests/it/contract.rs
> +        // assert_eq!(balances, Vec::from_iter(valid_balances.iter().copied()));
needed?

2022-12-18 11:04 UTC, gakonst approved these changes
love it

2022-12-18 11:05 UTC, merged