fix(middleware): oracles, tests
gakonst/ethers-rs pull request #1944
Opened 2022-12-16 22:57 UTC by DaniPopes

## Motivation

Old / non functioning API URLs

## Solution

- Replace gas_now url
- [deprecate eth_gas_station](https://twitter.com/ETHGasStation/status/1597341610777317376) and replace it in docs and tests with gas_now
- temporarily ignore etherchain tests which is failing in builds due to 404
- clean up parsing and gas calculation since every oracle was different
- add some default impls and derives
- export internal Response structs which were exposed in the query functions but were not exported at mod level
- add common Result type alias for gas_oracle
- add missing tests for oracles
- switch to a [different blocknative url](https://docs.blocknative.com/gas-platform#example-request)

*breaking:*
-  make blocknative api key optional
- change the some base oracles method from request to query for consistency
- change all oracle query methods to return just the Response struct and move parsing in other functions

## PR Checklist

-   [x] Added Tests
-   [x] Added Documentation
-   [ ] Updated the changelog
-   [x] Breaking changes

2022-12-16 23:44 UTC, mattsse requested changes
tysm!

It looks like this includes a lot of valuable but separate contributions, including some breaking changes I think.

I'd rather merge this in separate PRs, so it would be easier to merge this step by step.

Could you please split this as you see fit?

2022-12-17 00:02 UTC, DaniPopes commented
What do you mean by easier to merge? I think a lot of these changes will overlap with each other which would have the opposite effect - I don't think there's much point in splitting this, it's mostly just making the individual oracles and file structure consistent + fixing a few bugs and adding a few tests

I finished listing all changes and breaking changes

2022-12-17 00:06 UTC, mattsse commented
> What do you mean by easier to merge? I think a lot of these changes will overlap with each other which would have the opposite effect - I don't think there's much point in splitting this

this is good to know.

I just wanted to check this out before looking at it more closely because it looks like it has a lot of valuable corrections in it.

2022-12-18 11:45 UTC, gakonst approved these changes

2022-12-18 11:45 UTC, gakonst commented on ethers-middleware/src/gas_oracle/etherchain.rs
> +const URL: &str = "https://www.etherchain.org/api/gasPriceOracle";
https://twitter.com/milancermak/status/1604441584808103936 maybe we can use this https://etherchain.org/api/gasnow, which redirects to https://beaconcha.in/api/v1/execution/gasnow

2022-12-18 11:45 UTC, merged