fixed issue#2004 parsing solc verison with trailing newlines
gakonst/ethers-rs pull request #2005
Opened 2023-01-03 23:33 UTC by elizabethdinella

fixes #2004 

Need some guidance on creating test(s) and updating docs

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

2023-01-05 14:10 UTC, mattsse requested changes

2023-01-05 14:10 UTC, mattsse commented on ethers-solc/src/compile/mod.rs
> +            .filter(|l| !l.as_ref().unwrap().is_empty())
great,

now that I'm seeing this again, we can 
```suggestion
            .filter_map(Result::ok)
            .filter(|l| !l.trim().is_empty())
```
and get rid of the `map_err` entirely

2023-01-06 20:28 UTC, mattsse approved these changes
lgtm, tysm!

2023-01-09 05:26 UTC, gakonst approved these changes

2023-01-13 18:45 UTC, merged