feat(ethers-solc): extend model checker setting field
gakonst/ethers-rs pull request #2123
Opened 2023-02-08 08:02 UTC by wiasliaw

## Motivation

- extend model checker setting's field to open `invariants` flag.
- [invariants docs](https://docs.soliditylang.org/en/v0.8.18/smtchecker.html#reported-inferred-inductive-invariants) 

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

2023-02-08 09:10 UTC, mattsse requested changes
when was this introduced?

we probably need a check here

https://github.com/gakonst/ethers-rs/blob/e20bb715699280402c155a0abbfc82656582242e/ethers-solc/src/artifacts/mod.rs#L103-L105

2023-02-09 07:34 UTC, wiasliaw commented
@mattsse 
Found in [0.8.10](https://blog.soliditylang.org/2021/11/09/solidity-0.8.10-release-announcement/).

2023-02-09 09:10 UTC, mattsse approved these changes

2023-02-10 19:50 UTC, gakonst approved these changes
nice - i have not yet seen any prod codebases which use these extensively, would love to have some examples in foundry

2023-02-10 19:51 UTC, merged