refactor(abigen): derives, struct expansion
gakonst/ethers-rs pull request #2160
Opened 2023-02-17 07:41 UTC by DaniPopes

## Motivation

## Solution

Minor refactors that didn't make the cut for their own PR

- add more trait implementations and make existing ones more explicit (`impl Clone` -> `impl ::core::clone::Clone` etc)
- unify `expand_data_{struct,tuple}` to use a single generic function
- rename `event_derives` to `extra_derives` and standardize how `can_derive_default` is added to the final item derives
- replace empty `TokenStream` with `Option<TokenStream>`

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

2023-02-17 10:35 UTC, mattsse approved these changes
this is so much better.

tysm for showing this some love!

2023-02-17 10:35 UTC, mattsse commented on ethers-contract/ethers-contract-abigen/src/contract.rs
> +            /// More information at: <https://github.com/gakonst/ethers-rs>
great!

2023-02-17 10:35 UTC, mattsse commented on ethers-contract/ethers-contract-abigen/src/contract.rs
> +    extra_derives: Vec<Path>,
this is so much better :)

2023-02-18 21:11 UTC, gakonst requested changes
nice work!

2023-02-18 21:11 UTC, gakonst commented on ethers-contract/ethers-contract-abigen/src/contract/structs.rs
> +pub(crate) fn expand_struct(
clean!

2023-02-18 21:11 UTC, gakonst commented on ethers-contract/ethers-contract-abigen/src/contract.rs
> +            pub struct #name<M>(#ethers_contract::Contract<M>);
we'll need to resolve conflict with https://github.com/gakonst/ethers-rs/commit/9733b16afc5c35be4409b72c172d8f7405f45d7c

2023-02-19 07:19 UTC, DaniPopes commented on ethers-contract/ethers-contract-abigen/src/util.rs
>  }
Rewrote it to make it more idiomatic using more variables, don't think there's another way to do it

2023-02-20 00:53 UTC, merged

2023-02-20 00:53 UTC, gakonst commented
ty!