refactor(abigen): keep and use parsed spans
gakonst/ethers-rs pull request #2247
Opened 2023-03-10 16:53 UTC by DaniPopes

## Motivation

Keep spans around instead of unparsing into Strings

## Solution

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Updated the changelog
-   [ ] Breaking changes

2023-03-10 20:12 UTC, mattsse requested changes
looks great.

but I want to get rid of Abigen pub fields. don't think they need to be mutable or do they?

2023-03-10 20:12 UTC, mattsse commented on ethers-contract/ethers-contract-abigen/src/lib.rs
> +
why do we need pub access now?

2023-03-10 20:15 UTC, DaniPopes commented
They do for the builder, allows direct access to maps

2023-03-10 21:25 UTC, mattsse commented
since this is a public type, I'd rather have immutable getter functions.

2023-03-12 11:55 UTC, DaniPopes commented
Clippy unrelated, looks like a new lint dropped

2023-03-13 19:49 UTC, gakonst approved these changes

2023-03-13 19:49 UTC, merged