fix(core): re-export CallLogFrame from geth types
gakonst/ethers-rs pull request #2283
Opened 2023-03-20 16:00 UTC by jqphu

## Motivation

The CallLogFrame was not being exported from geth which made it
difficult to store all the logs using the ethers type.

## Solution

Export CallLogFrame so it's accessible publicly via `ethers::types`.

2023-03-20 16:03 UTC, mattsse approved these changes

2023-03-20 18:09 UTC, DaniPopes requested changes

2023-03-20 18:09 UTC, DaniPopes commented on Cargo.toml
> +futures-channel = "0.3.25"
what is this for?

2023-03-20 18:13 UTC, jqphu commented on Cargo.toml
> +futures-channel = "0.3.25"
Wrong fork.. sorry! Removing.

2023-03-20 18:34 UTC, jqphu commented
Was just testing this locally and realized I didn't make the internal fields public. Fixed and good to go now!

2023-03-21 02:06 UTC, prestwich approved these changes

2023-03-21 03:01 UTC, merged