Jepsen/mdbook
gakonst/ethers-rs pull request #2297
Opened 2023-03-23 20:03 UTC by 0xJepsen

I added some more to the documentation here

- [x] Events
- [x] Subscriptions

contributes to #2282

2023-03-26 20:23 UTC, prestwich requested changes
High-level changes:

It would be good to route users to the `abigen!`-based interfaces for accessing these tools, as they're simpler and higher level. This documentation is a good explanation of how abigen works under the hood

We should also mention the difference between `Event::stream` and `Event::subscribe`. the `stream` interface is polling, and will work with any provider, but have increased cost and latency. Subscribe is based on WS/IPC notifications, and is limited to those providers

2023-03-26 20:23 UTC, prestwich commented on book/events/events.md
> +Now, let's import the necessary components from the ethers-rs library:
Should be outside the code block?

2023-03-26 20:23 UTC, prestwich commented on book/events/events.md
> +pub new_value: U256,
indent?

2023-03-26 20:23 UTC, prestwich commented on book/events/events.md
> +prelude::\*,
indent. is the escape on the asterisk necessary?

2023-03-26 20:23 UTC, prestwich commented on book/subscriptions/subscriptions.md
> +use ethers::{prelude::\*,types::H256,};
is the escape necessary here?

2023-03-26 21:55 UTC, 0xJepsen commented on book/events/events.md
> +Now, let's import the necessary components from the ethers-rs library:
nice catch

2023-03-26 21:58 UTC, 0xJepsen commented
Thanks for the feedback, I went and made some of the easy changes. I have yet to distinguish the difference between `Event::stream` and `Event::subscribe` like you recommended but will look to getting around to it soon.

2023-04-09 22:35 UTC, prestwich commented
> Thanks for the feedback, I went and made some of the easy changes. I have yet to distinguish the difference between Event::stream and Event::subscribe like you recommended but will look to getting around to it soon.

did you intend to do this as part of this PR? or in a future one?

2023-04-25 16:16 UTC, prestwich commented
CI failures unrelated

2023-04-25 16:17 UTC, merged