Remove the eip712 feature flag and have it enabled by default. Fmt files
gakonst/ethers-rs pull request #2409
Opened 2023-05-09 13:44 UTC by dbelv

## Motivation
Closes https://github.com/gakonst/ethers-rs/issues/2408

## Solution
Remove feature flag enabling by default.

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Breaking changes

2023-05-09 13:47 UTC, dbelv commented
Muscle memory had me doing `cargo fmt` which is unfortunately why large amount of touched files within the same commit vs the actual implementation of the issue.

2023-05-09 14:32 UTC, dbelv commented
Sorry I have overloaded the PR for clippy fixes as well

2023-05-09 15:36 UTC, DaniPopes requested changes

2023-05-09 15:36 UTC, DaniPopes commented on ethers-contract/Cargo.toml
> -eip712 = []
Could you add them back here too?

2023-05-09 15:36 UTC, DaniPopes commented on ethers-core/Cargo.toml
> -eip712 = []
Same

2023-05-09 16:06 UTC, prestwich requested changes
keep the flag in the Cargo.toml. Removing it will break compilation for library consumers

2023-05-09 16:06 UTC, prestwich commented on ethers-core/README.md
> --   `eip712`: Provides the `Eip712` trait and derive procedural macro for EIP-712 encoding of typed data.
modify to say "does nothing"

2023-05-09 16:06 UTC, prestwich commented on ethers-core/src/types/signature.rs
> -#[cfg(feature = "eip712")]
combine with main impl block

2023-05-10 00:36 UTC, dbelv commented on ethers-contract/Cargo.toml
> -eip712 = []
Ah right, yep.

2023-05-10 06:00 UTC, DaniPopes approved these changes
Thanks!

2023-05-10 06:00 UTC, merged