Feature/wallet encrypt keystore
gakonst/ethers-rs pull request #2502
Opened 2023-07-09 08:25 UTC by 0xZerohero

## Motivation

This function is similar to Wallet::new_keystore, but instead of adding the a random private key to the file, it adds a key passed as a parameter.
This is handy when you want to safe an existing private key in an encrypted file.

This can also help with the implementation of https://github.com/foundry-rs/foundry/issues/5057

## Solution

## PR Checklist

-   [x] Added Tests
-   [x] Added Documentation
-   [ ] Breaking changes

2023-07-11 10:57 UTC, DaniPopes requested changes

2023-07-14 13:19 UTC, 0xZerohero commented on ethers-signers/src/wallet/private_key.rs
> +        let private_key = "6f142508b4eea641e33cb2a0161221105086a84584c74245ca463a49effea30b";
Sorry I'm on vacation and have very poor internet connection. I'll be able to check that next week, but I'm curious why the tests failed on CI, but work fine locally.

2023-07-21 10:39 UTC, 0xZerohero commented on ethers-signers/src/wallet/private_key.rs
> +        let private_key = "6f142508b4eea641e33cb2a0161221105086a84584c74245ca463a49effea30b";
Fixed

2023-07-25 12:56 UTC, DaniPopes approved these changes

2023-07-25 12:56 UTC, merged