feat(chain): add degen chain mainnet
gakonst/ethers-rs pull request #2778
Opened 2024-04-10 12:52 UTC by guidota

## Motivation

There is no support for Degen chain.

## Solution

Add Degen chain to `Chain`.

## PR Checklist

-   [ ] Added Tests
-   [ ] Added Documentation
-   [ ] Breaking changes

2024-04-10 12:56 UTC, mattsse requested changes
need spec update, see failing test

2024-04-10 14:15 UTC, guidota commented
Thank you for the feedback on my pull request. I'm a bit confused about the request to update the spec. The failing tests I see appear to be related to rate limiting (`daily request count exceeded, request rate limited`) rather than the changes I made. I've reviewed the code and don't see any issues with the functionality I've updated.

Could you please provide more context on which specific part of the spec you would like me to update? I want to make sure I address the right issue. Additionally, I've checked the clippy errors, and they don't seem directly related to the change I submitted.

Please let me know if you need any clarification or have additional information I should review. I'm happy to make any necessary updates to ensure my pull request is ready for merging.

2024-04-10 14:46 UTC, mattsse commented
ah sorry, could you please open the pr against in this repo

https://github.com/alloy-rs/chains

2024-04-10 16:30 UTC, guidota commented
Thanks for the help! 
PR here https://github.com/alloy-rs/chains/pull/57

2024-04-12 13:05 UTC, guidota commented
Revisiting this, can it be merged here too? 🙏🏼

2024-04-15 16:19 UTC, merged