fix(core): prevent chain_id from serializing for requests
gakonst/ethers-rs pull request #879
Opened 2022-02-07 22:33 UTC by Rjected

## Motivation
OpenEthereum seems to not have a `chainId` field in its [`TransactionRequest`](https://github.com/openethereum/openethereum/blob/main/crates/rpc/src/v1/types/transaction_request.rs#L32) type.

## Solution
This PR disables serialization for the `chain_id`, so we don't send it in RPC requests.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

2022-02-07 23:49 UTC, mattsse reviewed
hmm, this is a bit tricky, because I'm not sure what side-effects this could potentially cause, what does? since this is a client issue for openethereum
I believe in geth chainid is omitempty, so this approach seems fine. But not sure if there is some kind of check that chainids match so that tx intended for chain X are rejected on chain Y? so we'd lose that

alternatives:

* should we skip this instead based on the chainid?
* should we rather take the chain id if the client is OE, I believe we already have some calls that check the client first, definitely more effort, not ideal.

2022-02-08 19:42 UTC, Rjected commented
Since `chain_id` was [recently](https://github.com/gakonst/ethers-rs/pull/805) introduced to our request types, we shouldn't really be introducing any new issues by not serializing.

I'm not sure that alternative 1 (skip based on the chainid), or any solution that depends on _only_ the chainid would work since OE will not accept any chainId field. [Geth does have omitempty for the chainId](https://github.com/ethereum/go-ethereum/blob/2d20fed893faa894f50af709349b13b6ad9b45db/internal/ethapi/transaction_args.go#L36), but it would be up to us to ensure that the `chain_id` field matches that of the client when running `send_transaction`, `sign_transaction`, etc. This would probably prevent user error.

This would not be necessary for `send_raw_transaction`, since that depends on RLP, which should already include the chainid. [Geth does check the chainId](https://github.com/ethereum/go-ethereum/blob/2d20fed893faa894f50af709349b13b6ad9b45db/core/types/transaction_signing.go#L272), so if we were to do chainId checks there it would be in case other clients don't do these checks.

2022-02-08 19:44 UTC, mattsse requested changes
smol nit

2022-02-08 19:44 UTC, mattsse commented on ethers-core/src/types/transaction/request.rs
> +    #[serde(rename = "chainId")]
```suggestion
    #[serde(default, rename = "chainId")]
```

2022-02-08 19:50 UTC, Rjected commented on ethers-core/src/types/transaction/request.rs
> +    #[serde(rename = "chainId")]
added to both request and 1559 request

2022-02-08 20:00 UTC, gakonst approved these changes

2022-02-08 21:41 UTC, merged

2022-02-09 15:30 UTC, tarrencev commented
@Rjected I'm still running into this issue after updating foundry to use this PR

```
(code: -32602, message: Invalid params: unknown field `chainId`, expected one of `type`, `from`, `to`, `gasPrice`, `maxFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `maxPriorityFeePerGas`., data: None)
```

It looks like it is still serialized into the txn `\"chainId\":\"0x2a\"`

2022-02-09 15:33 UTC, tarrencev commented
Ah nevermind. I sanity checked forge paths and it was using an old path under `.cargo` rather than the one in `.foundry`