feat: cached provider PoC
gakonst/ethers-rs pull request #949
Opened 2022-02-22 14:24 UTC by gakonst

One idea on how we could do the cached provider. I don't really like the recurring serialization costs or the mutex on the requests map..makes me wonder this is not the right way to do it? would using sled or sqlite be worth it here, or overkill?

2022-02-24 22:13 UTC, mattsse requested changes

2022-02-24 22:13 UTC, mattsse commented on ethers-providers/src/cache.rs
> +        dbg!(&provider.cache());
```suggestion
```

2022-02-24 22:13 UTC, mattsse commented on ethers-providers/src/cache.rs
> +        let file = match File::options().write(true).read(true).create(true).open(&self.path) {
this should be `File::create`? which

> Opens a file in write-only mode. reate a file if it does not exist, and will truncate it if it does.

2022-02-24 22:13 UTC, mattsse commented on ethers-providers/src/cache.rs
> +    requests: DashMap<String, String>,
should this be <String, serde_json::Value>?

2022-02-24 23:11 UTC, gakonst commented
@brockelmore curious what you think on this approach?

2022-03-02 16:39 UTC, tynes commented
Depending on how forge implements its caching strategy, it might be useful to have a way to clear the cache

2022-03-03 16:14 UTC, gakonst commented
Closing - will make it part of the Forking provider on Foundry

2022-03-03 16:14 UTC, closed without merging